apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eoyebami@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: Z08513641YW2S9UOQL2LX
          accessKeyIDSecretRef:
            name: aws-cert-manager-creds
            key: accessKey
          secretAccessKeySecretRef:
            name: aws-cert-manager-creds
            key: secretKey
          role: arn:aws:iam::771474661311:role/cert-manager
